### ISSUE TITLE
mail notification: ssl/tls auto negotiation.

### ISSUE THREAD

**Issue by ArunMj** [ArunMj/groot#10]
as a part of new notification re implementation this should be done.
<pre> 
if security == auto:
   when port is
      25  -> try null, tls , ssl respectively until one succeed.
      587 -> tls | ssl | null respectively
      465 -> ssl | tls | null respectively
      else -> same as 25
   cache security type; so that next time no need to follow above hit-or-miss methods

</pre>

config.yml 
```yml
notifications:
    channels:
        mail:
            maximum_retries: 10
            retry_interval_seconds: 60
            retry_timeout: 600
            smtp:
                host: postbud220.trv.flytxt.com
                port: 25
                user: 
                password: 
                security: SSL | TLS | null | auto
```
